---
title: "Data Manipulation"
output: github_document
---
```{r setup, echo=FALSE, message=FALSE}
library(tidyverse)
```
This document will show how to "manipulate" data.
import two datasets that we're going to manipulate.

```{r}
litters_df=
  read.csv("data/FAS_litters.csv", na=c("NA", "", "."))

litters_df = janitor::clean_names(litters_df)

pups_df=
  read_csv("data/FAS_pups.csv", na=c("NA", "", "."))
pups_df = janitor::clean_names(pups_df)
```
## `select`

use select to select variables

```{r}
select(litters_df, group, litter_number, gd0_weight)
```

```{r}
select(litters_df, group:gd18_weight)
```
```{r}
select(litters_df, -pups_survive)
select(litters_df, starts_with("gd"))
select(litters_df, contains("pups"))
```

```{r}
select(litters_df, GROUP = group)

rename(litters_df, GROUP =group)

select(litters_df, litter_number, gd0_weight)

relocate(litters_df, litter_number, gd0_weight)
```

```{r}
select(pups_df, litter_number, sex, pd_ears)
```

## `filter`

```{r}
library(dplyr)
filter(litters_df, gd_of_birth ==19)
filter( litters_df, pups_born_alive > 5)


filter(litters_df, group == c("Low7", "Low8"))
filter(litters_df, group %in% c("Low7", "Low8"))

filter(litters_df, group %in% c("Low7", "Low8", pups_born_alive > 5))

filter(pup_df,sex==1)
filter(pup_df, pd_walk < 11, sex ==2)
```

```{r filter out rows with missing variables}
drop_na(litters_df)
filter(pup_df,sex=1)
```







## `mutate`


## `arrange`


## `piping`
